
<div id="pointofsale_box">
    <div id="tools" class='hide-400'>
        <span id="searching"><?php echo __('Searching your location'); ?></span>
    </div>
    <div id="map_canvas_pointofsale" class='hide-400'></div>
    <div id="pointofsale" class="alone">
        <div id="title">
            <?php echo __('All our store locations'); ?>
            <?php $countries = $block->getCountries(); ?>

            <div id="country_selection">
                <?php echo __('Select a country :'); ?>

                <select id="country_place">
                    <option value="*">
                        <?php echo __('All countries'); ?>
                    </option>
                    <?php foreach ($countries as $country): ?>
                        <option value="<?php echo $country['code']; ?>">
                            <?php echo $country['name']; ?>
                        </option>
                    <?php endforeach; ?>
                </select>
            </div>

            <?php $states = $block->getStates(); ?>
            <div id="state_selection">
                <?php echo __('Select a state :'); ?>

                <select id="state_place">
                    <option value="*">
                        <?php echo __('All states'); ?>
                    </option>
                    <?php foreach ($states as $state): ?>
                        <option value="<?php echo $state['code']; ?>">
                            <?php echo $state['name']; ?>
                        </option>
                    <?php endforeach; ?>
                </select>
            </div>
        </div>
        <div id="pointofsale_scroll">
            <?php foreach ($this->getPointofsale() as $place) : ?>
                <div class="place <?php echo $place->getCountryCode(); ?>">
                    <h3>
                        <a href="javascript:void(0)" class="go-to-place" id="<?php echo $place->getPlaceId(); ?>"><?php echo $place->getName(); ?></a>
                    </h3>
                    <div id="place_<?php echo $place->getPlaceId(); ?>" class="details" style="display:none">
                        <?php echo $block->getPosHelper()->getStoreDescription($place); ?>
                    </div>
                </div>
            <?php endforeach; ?>
        </div>
    </div>
</div>
<div id="dirRendererBlock">
    <div id="direction_title">
        <h3><?php echo __('Your directions') ?></h3>
        <span><a class="render_tool" href="javascript:PointOfSale.closeDirection()"><?php echo __('Close') ?></a></span> |
        <span><a class="render_tool" href="javascript:print()"><?php echo __('Print') ?></a>  </span>
    </div>
    <div id="directions"></div>

</div>

<?php if ($this->getRequest()->getModuleName() != "pickupatstore") : ?>
    <script type="text/javascript"  src="//maps.googleapis.com/maps/api/js?sensor=false&v=3&key=<?php echo $block->getGoogleApiKey(); ?>">
    </script>
<?php endif; ?>

<script type="text/javascript">
    W_GP = {
        strings: {
            getDirections: '<?php echo __("Get Directions"); ?>',
            showOnGoogleMap: '<?php echo __("Show on Google Map"); ?>',
            from: '<?php echo __("From"); ?>',
            noStoreLocated: '<?php echo __("No store located"); ?>',
            youAreHere: '<?php echo __("You are here"); ?>',
            theClosestStoreIs: '<?php echo __("The nearest store is"); ?>',
            noResultFound: '<?php echo __("No result found."); ?>',
            unableToFindYourLocation: '<?php echo __("Unable to find your location"); ?>',
            distanceCalculationFailed: '<?php echo __("Distance calculation failed"); ?>',
            showMyLocation: '<?php echo __("show my location"); ?>',
            changeMyLocation: '<?php echo __("change my location"); ?>',
            yourLocation: '<?php echo __("Your location"); ?>',
            findMe: '<?php echo __("Find me"); ?>',
            enterYourLocation: '<?php echo __("Enter your location (city, address, zipcode...)"); ?>',
            setANewLocation: '<?php echo __("Set a new location"); ?>',
            youDirections: '<?php echo __("Your directions"); ?>',
            close: '<?php echo __("Close"); ?>',
            close:                     '<?php echo __("Print"); ?>',
                    searchingYourLocation: '<?php echo __("Searching your location"); ?>',
            allOurStoreLocations: '<?php echo __("All our store locations"); ?>',
            selectACountry: '<?php echo __("Select a country"); ?>',
            allCountries: '<?php echo __("All countries"); ?>'


        },
        myAddress: null
    };
    require(["jquery", "mage/mage"], function ($) {
        $(function () {
            PointOfSale.places = <?php echo $block->getJsonData(); ?>;
            PointOfSale.__initialize();
        });
    });
</script>
